# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpotifyWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpotifyWidget(object):
    def setupUi(self, SpotifyWidget):
        SpotifyWidget.setObjectName("SpotifyWidget")
        SpotifyWidget.resize(466, 543)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 78, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 65, 67))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 34, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        SpotifyWidget.setPalette(palette)
        SpotifyWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        SpotifyWidget.setAutoFillBackground(False)
        self.pausePlay = QtWidgets.QPushButton(SpotifyWidget)
        self.pausePlay.setGeometry(QtCore.QRect(160, 420, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setBold(True)
        font.setWeight(75)
        self.pausePlay.setFont(font)
        self.pausePlay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pausePlay.setObjectName("pausePlay")
        self.trackTitleLabel = QtWidgets.QLabel(SpotifyWidget)
        self.trackTitleLabel.setGeometry(QtCore.QRect(40, 330, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.trackTitleLabel.setFont(font)
        self.trackTitleLabel.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.trackTitleLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.trackTitleLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackTitleLabel.setText("")
        self.trackTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trackTitleLabel.setObjectName("trackTitleLabel")
        self.profileLabel = QtWidgets.QLabel(SpotifyWidget)
        self.profileLabel.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.profileLabel.setText("")
        self.profileLabel.setObjectName("profileLabel")
        self.changeDeviceCombo = QtWidgets.QComboBox(SpotifyWidget)
        self.changeDeviceCombo.setGeometry(QtCore.QRect(305, 20, 161, 20))
        self.changeDeviceCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeDeviceCombo.setEditable(False)
        self.changeDeviceCombo.setCurrentText("")
        self.changeDeviceCombo.setObjectName("changeDeviceCombo")
        self.trackArtistLabel = QtWidgets.QLabel(SpotifyWidget)
        self.trackArtistLabel.setGeometry(QtCore.QRect(50, 370, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(10)
        font.setItalic(True)
        self.trackArtistLabel.setFont(font)
        self.trackArtistLabel.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.trackArtistLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.trackArtistLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackArtistLabel.setText("")
        self.trackArtistLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trackArtistLabel.setObjectName("trackArtistLabel")
        self.albumArtLabel = QtWidgets.QLabel(SpotifyWidget)
        self.albumArtLabel.setGeometry(QtCore.QRect(130, 120, 200, 200))
        self.albumArtLabel.setText("")
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.userInfoLabel = QtWidgets.QLabel(SpotifyWidget)
        self.userInfoLabel.setGeometry(QtCore.QRect(70, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.userInfoLabel.setFont(font)
        self.userInfoLabel.setText("")
        self.userInfoLabel.setObjectName("userInfoLabel")
        self.volSlider = QtWidgets.QSlider(SpotifyWidget)
        self.volSlider.setGeometry(QtCore.QRect(20, 510, 131, 16))
        self.volSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.volSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volSlider.setObjectName("volSlider")
        self.volLabel = QtWidgets.QLabel(SpotifyWidget)
        self.volLabel.setGeometry(QtCore.QRect(170, 510, 31, 17))
        self.volLabel.setObjectName("volLabel")
        self.creditLabel = QtWidgets.QLabel(SpotifyWidget)
        self.creditLabel.setGeometry(QtCore.QRect(290, 510, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(8)
        font.setItalic(True)
        self.creditLabel.setFont(font)
        self.creditLabel.setObjectName("creditLabel")
        self.prevPB = QtWidgets.QPushButton(SpotifyWidget)
        self.prevPB.setGeometry(QtCore.QRect(40, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.prevPB.setFont(font)
        self.prevPB.setObjectName("prevPB")
        self.nextPB = QtWidgets.QPushButton(SpotifyWidget)
        self.nextPB.setGeometry(QtCore.QRect(370, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.nextPB.setFont(font)
        self.nextPB.setObjectName("nextPB")
        self.deviceLabel = QtWidgets.QLabel(SpotifyWidget)
        self.deviceLabel.setGeometry(QtCore.QRect(310, 3, 51, 17))
        self.deviceLabel.setObjectName("deviceLabel")
        self.searchLabel = QtWidgets.QLabel(SpotifyWidget)
        self.searchLabel.setGeometry(QtCore.QRect(40, 80, 51, 17))
        self.searchLabel.setObjectName("searchLabel")
        self.searchEdit = QtWidgets.QLineEdit(SpotifyWidget)
        self.searchEdit.setGeometry(QtCore.QRect(100, 80, 301, 25))
        self.searchEdit.setObjectName("searchEdit")

        self.retranslateUi(SpotifyWidget)
        QtCore.QMetaObject.connectSlotsByName(SpotifyWidget)

    def retranslateUi(self, SpotifyWidget):
        _translate = QtCore.QCoreApplication.translate
        SpotifyWidget.setWindowTitle(_translate("SpotifyWidget", "Spotify"))
        self.pausePlay.setText(_translate("SpotifyWidget", "pause / play"))
        self.volLabel.setText(_translate("SpotifyWidget", "vol"))
        self.creditLabel.setText(_translate("SpotifyWidget", "Made by Andrew St. Pierre"))
        self.prevPB.setText(_translate("SpotifyWidget", "<--"))
        self.nextPB.setText(_translate("SpotifyWidget", "-->"))
        self.deviceLabel.setText(_translate("SpotifyWidget", "Device:"))
        self.searchLabel.setText(_translate("SpotifyWidget", "Search:"))


